spring:
  jpa:
    # 전송쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true

  sql:
    init:
      # data.sql 자동 실행 안함
      #mode: never

  datasource:
    url: jdbc:mysql://192.168.0.26:3306/movie
    username: ahncho
    password: dkswh18
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: false

#================================================
#  # db 연결?
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#
#  # 데이터 확인 localhost:8080/h2-console
#  h2:
#    console:
#      enabled: true
#================================================
#h2 대신에 mysql을 사용한다

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot
# yaml 은 들여쓰기를 사용하여 계층을 나타냄.